#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "DemoSquare"
# OpenGraph / Twitter Card metadata
description = "DemoSquare automates your political monitoring with machine learning so that you save time, reduce risks, and increase your impact."
author = "DemoSquare"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "DemoSquare automates your political monitoring with machine learning so that you save time, reduce risks, and increase your impact."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "Copyright &copy; <script>document.write(new Date().getFullYear())</script> DemoSquare"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "EPFL INDY<br>Station 14<br>1015 Lausanne<br>Switzerland"
phone = ["+41 21 693 56 10"]
email = ["contact@demosquare.ch"]
# phone = ["+704-555-0127", "+205-857-2321", "+002-569-6969"]
# email = ["info@andromeda.io", "smith@anderson.io", "john@anderson.io"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Buy Premium"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Become an Early Adopter!"
content = "DemoSquare is currently under development. Become an early adopter <br>or learn more about us by sending us an email."
button = "Contact us"
button_link = "mailto:contact@demosquare.ch"

############################# social site ########################
# [[social]]
# title = "Andromeda"
# icon = "lab la-facebook-f" # https://icons8.com/line-awesome
# link = "#!"

# [[social]]
# title = "AndromedaTweet"
# icon = "lab la-twitter"  # https://icons8.com/line-awesome
# link = "#!"

# [[social]]
# title = "AndromedaIn"
# icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
# link = "#!"

# [[social]]
# title = "AndromedaPin"
# icon = "lab la-pinterest" # https://icons8.com/line-awesome
# link = "#!"
